# 微服务注册到 eureka。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
server:
  port: 9013
spring:
  application:
    name: ihrm-employee  # 指定服务名。
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.142.161:3307/ihrm?characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  redis:
    host: 192.168.142.161
    port: 6379

